#
# Copyright (c) 2021-2025 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/carbynestack.github.io.
#
# SPDX-License-Identifier: Apache-2.0
#
nav:
  - Home: index.md
  - Documentation:
      - Getting Started:
          - documentation/getting-started/index.md
          - Overview: documentation/getting-started/overview.md
          - Prerequisites: documentation/getting-started/prerequisites.md
          - Deployment:
              - documentation/getting-started/deployment/index.md
              - Manual:
                  - documentation/getting-started/deployment/manual/index.md
                  - Platform Setup: documentation/getting-started/deployment/manual/platform-setup.md
                  - Stack: documentation/getting-started/deployment/manual/stack.md
              - Infrastructure as Code:
                  - documentation/getting-started/deployment/infrastructure-as-code/index.md
                  - Local: documentation/getting-started/deployment/infrastructure-as-code/local.md
          - Configuring the CLI: documentation/getting-started/cli.md
          - Millionaires Problem: documentation/getting-started/millionaires.md
      - Reference:
          - API Specification:
              - documentation/reference/api-specification/index.md
              - Castor: documentation/reference/api-specification/castor.md
              - Amphora: documentation/reference/api-specification/amphora.md
              - Ephemeral: documentation/reference/api-specification/ephemeral.md
  - Blog: https://blog.carbynestack.io
  - Community:
      - Participate: community/participate.md
      - Ecosystem: community/ecosystem.md
      - Events:
          - community/events/index.md
          - CarbyneStackCon '24:
              - community/events/csc24/index.md
          - CarbyneStackCon '23:
              - community/events/csc23/index.md
          - CarbyneStackCon '22:
              - community/events/csc22/index.md
      - Media Coverage: community/media-coverage.md
      - Opportunities: community/opportunities.md
      - Google Summer of Code: community/gsoc.md
      - Acknowledgements: community/acknowledgements.md
